spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5432/user_db
    username: user_db_user
    password: user_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  profiles:
    active: dev

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.vercel.userservice: DEBUG
    org.seasar.doma: DEBUG

jwt:
  secret: mySecretKey
  expiration: 86400000
