version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: vercel-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: vercel_user
      POSTGRES_PASSWORD: vercel_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - vercel-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: vercel-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - vercel-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  vercel-network:
    driver: bridge

